# Generated by Django 3.0.4 on 2020-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name', max_length=500)),
                ('time', models.DateTimeField(help_text='Time')),
                ('text', models.TextField(help_text='Text')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
