# Generated by Django 3.0.4 on 2020-04-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200404_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.URLField(default='https://hh.ru/employer-logo/3184173.png', help_text='Picture'),
        ),
    ]
