# Generated by Django 3.0.4 on 2020-04-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200404_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='e_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
