# Generated by Django 3.0.4 on 2020-04-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_invite_e_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='submit',
            field=models.IntegerField(),
        ),
    ]
