# Generated by Django 3.0.4 on 2020-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200404_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('name1', models.CharField(max_length=500)),
                ('name2', models.CharField(max_length=500)),
            ],
        ),
    ]
